//
//  ConstantTexts.swift
//  Lawyer
//
//  Created by Aman Kumar on 18/07/20.
//  Copyright © 2020 Hephateus. All rights reserved.
//

import Foundation
struct ConstantTexts{
    
    //MARK: - App Specific
    static let  AppName                             =      APP_NAME
    static let  requestTimedOut                     =      "Request timed out"
    static let  noInterNet                          =      "No Internet Connection"
    static let  Invalid_URL                         =      "Invalid URL"
    static let  errorMessage                        =      "There is some error occured. Please try again later."
    static let  somethingWentMessage                =      "Something went wrong!"
    static let  authToken                           =      "authToken"
    static let  unexpectedIndexPath                 =      "Unexpected Index Path"
    static let  empty                               =      String()
    static let  deviceType                          =      "2"
    static let  blankSpace                          =      " "
    static let  newLineBreak                        =      "\n"
    static let  supportLink                         =      "support@allindialegal.com"
    static let  supportConta                        =      "1800-419-9661"
    static let  mod20                               =      "%20"
    static let  simulatorToken                      =      "SIMULATOR_TOKEN"
    static let  razorpayTestKey                     =      "rzp_test_NCjJ2F3uUBhH6l"
    static let  razorpayLiveKey                     =      "rzp_live_haSkjQFtIsqA8H"
    
    
    //TODO: Animation
    static let  wallet_animation                    =      "wallet_animation"
    static let  Law                                 =      "Law"
    static let  Construction                        =      "construction"
    static let  ContactUs                           =      "ContactUs"
    static let  Halo                                =      "Halo"
    static let  Wave                                =      "Wave"
    
    static let  EmptyBox                            =      "EmptyBox"
    static let  NoInternetConnectionEmptyState      =      "NoInternetConnectionEmptyState"
    static let  NoConnection                        =      "NoConnection"
    static let  EmptyBoxNew                         =      "EmptyBoxNew"
    static let  SomeThingWentWrong                  =      "SomeThingWentWrong"
    static let  Invalid_URLA                        =      "Invalid_URL"
    static let  Loader                              =      "loader"
    static let  Upload_filesHeader                  =      "Upload_filesHeader"
    static let  search_doc                          =      "search_doc"
    static let  Sucess_Lottie                       =      "Sucess_Lottie"
    
    //TODO: Label Text
    static let  paymentDoneLT                       =      "Payment done"
    static let  Payment_PendingLT                   =      "Payment pending"
    static let  UploadLT                            =      "Upload"
    static let  DefaultTimeLT                       =      "00:00:00"
    static let  RecordLT                            =      "Record"
    static let  StopRecordLT                        =      "Stop"
    static let  LawyerNameLT                        =      "Lawyer Name"
    static let  DateLT                              =      "Date"
    static let  BookingTimeLT                       =      "Booking time"
    static let  TimeLT                              =      "Time"
    static let  ConsultationCostLT                  =      "Consultation Cost"
    static let  FooterLT                            =      "You will receice a confirmation email with your consultation details.\nClick the Continue button to describe your query so that the lawyer will be able to assist you better."
    static let  ConsultationTypeLT                  =      "Consultation Type"
    static let  ConsultationCaseTypeLT              =      "Consultation Case Type"
    static let  CallConsultationLT                  =      "Call Consultation"
    static let  MeetConsultationLT                  =      "Meet Consultation"
    static let  YourBalanceLT                       =      "Your Balance"
    
    static let  SelectYourOptionLT                  =      "Select your option"
    static let  GalleryLT                           =      "Gallery"
    static let  DocumetsLT                          =      "Documents"
    static let  CameraLT                            =      "Camera"
    static let  ConsultationPaymentLT               =      "Consultation Payment"
    
    static let  UploadDocumentInsLT                 =      "If you have any additional documents, kindly upload the same in the above space."
    static let  UploadDocumentLT                    =      "Upload document"
    static let  DocumentUploadLT                    =      "Document uploaded"
    static let  AdditionalInfoLT                    =      "Give a brief description of your query to make the understand your query"
    
    static let  AdditionalQuerLT                    =      "Create your query related to any legal issue and you will recieve some advice by our expert"
    
    static let  QueryStatusLT                       =      "Your Query is created, you will be reported soon"
    static let  QuestionLT                          =      "Question: "
    static let  AnswerLT                            =      "Answer: "
    static let  OpenLT                              =      "Open"
    static let  ResolvedLT                          =      "Resolved"
    
    static let  NeedHelp_LT                         =      "Need Help?\nTalk to an Expert."
    static let  Education_LT                        =      "Education"
    static let  CallCharges_LT                      =      "Call charges"
    static let  ConsultationCharges_LT              =      "Consultation charges"
    static let  ConsultationFees_LT                 =      "Consultation fees"
    static let  ProfessionalHistory_LT              =      "Professional history"
    
    static let  NotAvaila_LT                        =      "Not available"
    static let  MailUsTitle_LT                      =      "For enquiries, mail us"
    static let  CallUsTitle_LT                      =      "For enquiries, call us on"
    
    static let  RateUsInstruction_LT                =      "Rate\n\nWould you mind stopping for a moment to rate us?"
    static let  Link_LT                             =      "\(APP_NAME) app link"
    static let  FAQs_LT                             =      "FAQ's"
    static let  Share_LT                            =      "Share"
    static let  Custom_Payment_LT                   =      "Custom Payment"
    static let  PaymentSuccessfull_LT               =      "Payment Successful"
    static let  RateUs_LT                           =      "Rate Us"
    static let  AboutUs_LT                          =      "About Us"
    static let  UnderConstruction_LT                =      "Our app is in under construction."
    static let  WeBackSoon_LT                       =      "We'll be back soon."
    static let  ContactUs_LT                        =      "Contact Us"
    static let  LogOut_LT                           =      "Logout"
    static let  Pending_LT                          =      "Pending"
    static let  QueryReso_LT                        =      "Your query will be resolved within next 18 hours."
    
    static let  Total_LT                            =      "Total"
    static let  MorningLT                           =      "Morning"
    static let  AfternoonLT                         =      "Afternoon"
    static let  EveningLT                           =      "Evening"
    static let  AM_LT                               =      "AM"
    
    static let  Delete_LT                           =      "Delete"
    static let  PM_LT                               =      "PM"
    static let  PaySummary_LT                       =      "Payment Summary"
    static let  UserDetail_LT                       =      "User Details"
    static let  ConsultationDetail_LT               =      "Consultation Details"
    static let  OriginalPrice_LT                    =      "Original Price"
    static let  CouponApplied_LT                    =      "Coupon Applied"
    static let  Gst_LT                              =      "GST @"
    static let  Gst_AppliedLT                       =      "GST Applied"
    static let  Payment_MethodLT                    =      "Payment method"
    static let  Gst_ValueLT                         =      "18%"
    static let  ServiceProviders_LT                 =      "Service Provider's GSTIN"
    static let  Per_LT                              =      "%"
    static let  MoreLT                              =      "More"
    static let  NeedQuickConsultationLT             =      "Need quick consultation"
    static let  GetReplyLT                          =      "Get on reply within 18 hours"

    static let  HomeLT                              =      "Home"
    static let  BlogsLT                             =      "Blogs"
    static let  OrdersLT                            =      "Orders"
    static let  OrdersDateLT                        =      "Order date"
    static let  OrdersTimeLT                        =      "Order time"
    static let  AdvLT                               =      "Adv. "
    static let  FlatFeesLT                          =      "Flat Fees"
    static let  CouponsLT                           =      "Coupons"
    static let  YouAreInLT                          =      "You are in"
    static let  TrademarkLT                         =      "Trademark and copyright"
    static let  SexualAbuseLT                       =      "Sexual Abuse"
    static let  StampParerAndNotaryLT               =      "Stamp Paper and Notary"
    static let  StartUpLT                           =      "Start Up"
    static let  TaxLT                               =      "Tax"
    static let  WillsLT                             =      "Wills"
    static let  AccidentsLT                         =      "Accidents"
    static let  BookAppointmentLT                   =      "Book Appointment"
    static let  BankingLT                           =      "Banking"
    static let  BusinessLawyersLT                   =      "Business Law"
    static let  ChildCustodyLT                      =      "Child Custody"
    static let  CivilLawyersLT                      =      "Civil Lawyers"
    static let  CommercialContractsLT               =      "Commercial Contracts"
    static let  ConsumerGrivancesLT                 =      "Consumer Grieviances"
    static let  CovidLT                             =      "COVID-19"
    static let  CriminalLawyersLT                   =      "Criminal Law"
    static let  FinanceLawLT                        =      "Finance Law"
    static let  ImmigrationLT                       =      "Immigration"
    static let  ITRLT                               =      "Income Tax Return"
    static let  LabourIssuesLT                      =      "Labour Issues"
    static let  LandlordTenantLT                    =      "Landlord/Tenant"
    static let  MerrigeRegistrationLT               =      "Marriage Registration"
    static let  MedicalNegligenceLT                 =      "Medical Negligence"
    static let  OthersLT                            =      "Others"
    static let  OthersServicesLT                    =      "Other services"
    static let  PersonalInjuryLT                    =      "Personal Injury"
    static let  RaggingLT                           =      "Ragging"
    static let  RecoveryLT                          =      "Recovery"
    static let  PropertyLT                          =      "Property"
    static let  DishonourOfChequesLT                =      "Dishonour of Cheques"
    static let  DivorceLT                           =      "Divorce"
    static let  DocumentationLT                     =      "Documentation"
    static let  DefaultFeeValueLT                   =      "N/A"
    static let  DefaultOffsetValueLT                =      "10"
    static let  DomesticVoilenceLT                  =      "Domestic Voilence"
    static let  EmployementLT                       =      "Employment"
    static let  FamilyLT                            =      "Family"
    static let  NALT                                =      "NA"
    static let  AnyLT                               =      "Any"
    static let  ZeroLT                              =      "0"
    static let  ExperienceLT                        =      "Experience"
    static let  CaseTypeLT                          =      "Case Type"
    static let  StarLT                              =      "*"
    static let  YrsLT                               =      "yrs"
    static let  CallLT                              =      "Call"
    static let  MeetLT                              =      "Meet"
    static let  CurLT                               =      "₹"
    static let  CountryCodeLT                       =      "+91"
    static let  DashLT                              =      "-"
    static let  SelectCityLT                        =      "Select city :-"
    static let  SelectLT                            =      "Select :-"
    static let  ResendInLT                          =      "Resend in"
    static let  LoadingLT                           =      "Loading..."
    static let  ChooseLT                            =      "Choose"
    static let  ChooseDecLT                         =      "A specialist lawyer of chartered accountant based on your case or requirement."
    static let  CityLT                              =      "City"
    static let  ExpertiseLT                         =      "Expertise"
    static let  LowWalletLT                         =      "Your wallet amount is low"
    
    static let  RateLawyerLT                         =      "If you rate our lawyer. It will definitely help us"
    
    static let  Expert_AssignedLT                   =      "Lawyer Assigned"
    static let  OrderCompletedLT                    =      "Order Completed"
    static let  Order_completedLT                   =      "Consultation completed"
    static let  LanguageLT                          =      "Language"
    static let  CosultationCompletedLT              =      "Consultation Completed!"
    static let  CosultationCompletedNewLT           =      "Your review for our lawyer"
    static let  CosultationCompletedInsLT           =      "Your consultation is successfully completed, Thank you for consultation with us."
    static let  CompareLT                           =      "Compare"
    static let  CompareDecLT                        =      "Multiple lawyers in every category. Choose on the basis of their charges, language and experience."
    
    static let  BookLT                              =      "Book"
    static let  BookDec1LT                          =      "A telephonic consultation on your preferred and relex"
    static let  BookDec2LT                          =      "sends you notifications and reminders."
    
    
    static let  EnterOTP1_LT                        =      "Enter OTP"
    static let  EnterOTP2_LT                        =      "OTP has been sent send to your mobile number."
    static let  VarificationCode_LT                 =      "Verification Code"
    static let  HaveGSTIN_LT                        =      "Do you have GSTIN?"
    static let  HaveGSTIN_Ins_LT                    =      "If you are registered under GST, please provide your GSTIN to clain input TAX Credit under the GST Regulations."
    
    static let  PleaseVarify_LT                     =      "Please Verify"
    
    static let  LawyerIns_LT                        =      "Register here to create your profile as a lawyer with us. Once your profile is approved, you can start building your client network and provide consultations."
    
    static let  CustomerIns_LT                      =      "Register with us as a customer and gain access to a wide network of lawyers for consultations and legal counselling."
    
    
    static let  CustomerIns_New_LT                  =      "Connect with us as a customer and gain access to a wide network of lawyers for consultations and legal counselling."
    
    static let  CompanyGSTIN_LT                     =      "27AAPFU0939F1ZV"
    static let  MyRecording_LT                      =      "myRecording.m4a"
    static let  Categories_LT                       =      "Category"
    static let  Select_categories_LT                =      "Select category:-"
    
    static let  YourLegalExpert_LT_1                =      "Your legal expert is "
    static let  YourLegalExpert_LT_2                =      ",he/she will contact you within 24 hours. You can write to him/her at "
    
    static let  YourLegalExpert_LT_3                =      "Your appointment date is: "
    static let  YourLegalExpert_LT_4                =      " and"
    static let  YourLegalExpert_LT_5                =      " time is: "
    
    static let  ReferText_LT                        =      "Refer \(AppName) to your friends"
    static let  Notified_LT                         =      "Get notified once your legal friends advice"
    static let  CashBack_LT                         =      "You and your friends get cashback"
    static let  Unique_LT                           =      "Your unique code"
    static let  ShareY_LT                           =      "Share your link to earn:"
    static let  FB_LT                               =      "Facebook"
    static let  WhatsApp_LT                         =      "Whatsapp"
    static let  Message_LT                          =      "Message"
    
    //TODO: Header Title Text
    static let  OrdersHT                            =      "Orders"
    static let  ReferAndEarnHT                      =      "Refer & Earn"
    static let  QuerisHT                            =      "Queries"
    static let  OrdersStatusHT                      =      "Order status"
    static let  QueryStatusHT                       =      "Query status"
    static let  CategoriesHT                        =      "Categories"
    static let  PaymentHT                           =      "Payment"
    static let  LoginHT                             =      "Login"
    static let  SignupHT                            =      "Signup"
    static let  VarificationHT                      =      "Verification"
    static let  MoreHT                              =      "More"
    static let  UnderCHT                            =      "Under construction"
    static let  LawyerDetailsHT                     =      "Lawyer details"
    static let  UploadDocumentHT                    =      "Upload Document (Optional)"
    static let  FreeCunsultationHT                  =      "Free Consultation"
    static let  ChooseServiceHT                     =      "Choose service"
    static let  ChooseCityHT                        =      "Choose city"
    
    
    //TODO: Button Title Text
    static let  SelectCityBT                        =      "Select city"
    static let  OkBT                                =      "Ok"
    static let  XBT                                 =      "x"
    static let  CancelBT                            =      "Cancel"
    static let  MeetBT                              =      "MEET"
    static let  ClearFiltersBT                      =      "Clear Filters"
    static let  ChangeDateAndTimeBT                 =      "Change Date & Time"
    static let  ClearFiltersStateBT                 =      "Are you sure?\nyou want to clear all filters!"
    static let  CallBT                              =      "CALL"
    static let  LIST_VIEW_BT                        =      "LIST VIEW"
    static let  MAP_VIEW_BT                         =      "MAP VIEW"
    static let  PROCEED_BT                          =      "PROCEED"
    static let  SKIP_BT                             =      "SKIP"
    static let  NEXTC_BT                            =      "NEXT"
    static let  LawyerBT                            =      "For Lawyer"
    static let  CustomerBT                          =      "For Customer"
    static let  SendOTP_BT                          =      "Send OTP"
    static let  GoToHome_BT                         =      "Go to Home"
    static let  GoToOrderStatus_BT                  =      "Go to Order Status"
    static let  BookConsul_BT                       =      "Book Consultation"
    static let  CheckOut_BT                         =      "Checkout"
    static let  Done_BT                             =      "Done"
    static let  ResendOTP_BT                        =      "Resend OTP"
    static let  Register_BT                         =      "Register"
    static let  DontHaveBT                          =      "Don't have an account?"
    static let  AlreadyHaveBT                       =      "Already Registered with us?"
    static let  SignUpAsC_BT                        =      "Sign Up."
    static let  SignUpAsL_BT                        =      "Sign Up as a Lawyer."
    static let  Clear_BT                            =      "Clear"
    static let  Apply_BT                            =      "Apply"
    static let  Copy_BT                             =      "Copy"
    static let  Use_Wallet_BT                       =      "  Use wallet amount to pay"
    static let  Applied_BT                          =      "Applied"
    static let  Submit_BT                           =      "Submit"
    static let  RequestCallBack_BT                  =      "Request a Callback"
    static let  Referal_BT                          =      "Referral"
    static let  Earning_BT                          =      "Earning"
    static let  RateLawyer_BT                       =      "Rate Lawyer"
    
    static let  Next_BT                             =      "NEXT"
    static let  LogInAsC_BT                         =      "Sign In as a Customer."
    static let  LogInAsL_BT                         =      "Sign In as a Lawyer."
    static let  Varify_BT                           =      "Verify"
    static let  DidntRecieve_BT                     =      "Didn't reveive the verification OTP?"
    static let  ResendAgain_BT                      =      "Resend again"
    
    static let  SignUpAsC_New_BT                    =      "Sign Up As Customer"
    static let  SignUpAsL_New_BT                    =      "Sign Up As Lawyer"
    static let  Start_Cuslutation_With_New_BT       =      "Start Consultation with lawyer"
    static let  Cuslutation_For_Free_BT             =      "Consultation for free"
    //TODO: Placeholder Text
    static let  MobileNumberPH                      =      "Mobile Number"
    static let  ContactNumberPH                     =      "Contact Number"
    static let  FullNamePH                          =      "Full Name"
    static let  NamePH                              =      "Name"
    static let  EmailAddressPH                      =      "Email Address"
    static let  EmailPH                             =      "Email"
    static let  CommentPH                           =      "Comment"
    static let  WriteCommentPH                      =      "Write your query here..."
    static let  WriteCommentNewPH                   =      "Write your comment here..."
    static let  KeywordsPH                          =      "Keywords"
    static let  Search_PH                           =      "Search"
    static let  GSTIN_PH                            =      "GSTIN*"
    static let  C_Name_PH                           =      "Company/Firm's Name (as per GSTIN)*"
    static let  C_Address_PH                        =      "Company/Firm's Address (as per GSTIN)*"
    static let  CouponCode_PH                       =      "Enter coupon code here"
    static let  AddNoteHere_PH                      =      "Add a note here"
    static let  State_PH                            =      "State*"
    
    
    //TODO: Alert Text
    static let  EnterGSTINNumberALERT               =      "Please enter GSTIN number."
    static let  EnterValidGSTINNumberALERT          =      "Please enter a valid GSTIN number."
    static let  SelectGSTIN_DD_ALERT                =      "Please select drop down."
    static let  SelectGSTINSTATE_DD_ALERT           =      "Please select state."
    static let  EnterCorFNameALERT                  =      "Please enter company/firm's name."
    static let  EnterValidCorFNameALERT             =      "Please enter valid company/firm's name."
    static let  EnterCorFAddressALERT               =      "Please enter company/firm's address."
    static let  EnterValidCorFAddressALERT          =      "Please enter valid company/firm's address."
    static let  WantToLogoutALERT                   =      "Are you sure?\nYou want to Log out!"
    static let  WantToDelRecALERT                   =      "Are you sure?\nYou want to to delete recorded audio!"
    static let  WantToDeleteDocuALERT               =      "Are you sure?\nYou want to delete uploaded document!"
    static let  RatedSuccessfullyALERT              =      "Thanks for you rating."
    static let  ContactYouSoonALERT                 =      "We'll contact you soon."
    static let  NoDataFoundALERT                    =      "No data found!"
    static let  NoOrdersFoundALERT                  =      "No orders found!"
    static let  NoDocumentUploadedYetALERT          =      "No document uploaded yet!"
    static let  DontHaveMicrophoneALERT             =      "Don't have access to use your microphone."
    
    static let  EnterMobileNumberALERT              =      "Please enter mobile number."
    static let  EnterValidMobileNumberALERT         =      "Please enter valid mobile number."
    
    static let  EnterFullNameALERT                  =      "Please enter full name."
    static let  EnterValidFullNameALERT             =      "Please enter valid full name."
    
    static let  EnterEmailALERT                     =      "Please enter email."
    static let  EnterValidEmailALERT                =      "Please enter valid email."
    
    static let  EnterOTPALERT                       =      "Please enter OTP."
    static let  EnterValidOTPALERT                  =      "Please enter valid OTP."
    
    static let  SelectCityALERT                     =      "Please select city."
    static let  EnterCommentALERT                   =      "Please write a comment."
    static let  EnterRateCommentALERT               =      "Please rate lawyer or write a comment."
    static let  SelectFilterALERT                   =      "Please select atleast one filter."
    static let  SelectTimeSlotALERT                 =      "Please select time slot."
    static let  SelectCaseTypeALERT                 =      "Please select case type."
    static let  EnterDescriptionALERT               =      "Please enter description."
    static let  EnterCouponCodeALERT                =      "Please enter coupon code."
    
    static let  EnterSelectCategoryALERT            =      "Please select category."
    
    static let  cameraAlert                         =      "Device has no camera."
    static let  chooseOneALERT                      =      "Already selected document.\nYou can pick only one document."
    static let  chooseNextDateALERT                 =      "Sorry!\n\nNo appointment time found on current date.\nYou can pick appointment from next date."
    static let  chooseOneRecordingALERT             =      "Already recorded an audio.\nYou can record only one audio."
    static let  recordingFailALERT                  =      "Recording failed."
    static let  audioFileMissingALERT               =      "Audio file is missing."
    
    //TODO: User defaults key
    static let  tourOverUDK                         =      "TOUR_OVER"
    static let  deviceToken                         =      "DEVICE_TOKEN"
    static let  deviceID                            =      "DEVICE_ID"
    static let  orderID                             =      "ORDER_ID"
    static let  paymentDone                         =      "PAYMENT_DONE"
    static let  userToken                           =      "USER_TOKEN"
    static let  hitQueryService                     =      "HIT_QUERY_SERVICE"
    static let  hitOrderService                     =      "HIT_ORDER_SERVICE"
    static let  mobile_logo                         =      "MOBILE_LOGO"
    static let  hitEarnedService                    =      "HIT_EARNED_SERVICE"
    static let  changeToQuery                       =      "CHANGE_TO_QUERY"
    static let  hitOrderStatusService               =      "HIT_ORDER_STATUS_SERVICE"
    static let  selectedCity                        =      "SELECTED_CITY"

    //TODO: Static values for api keys
    static let IpAddress_Key                        =      "0.0.0.0"
    
    //TODO: Storyboard Title
    static let  AuthSBT                             =      "Auth"
    static let  LaunchSBT                           =      "Launch"
    static let  TabBarSBT                           =      "TabBar"
    static let  HomeSBT                             =      "Home"
    
    
    //TODO: Errors domain
    static let  Network_Error                       =      "Network Error"
    static let  URL_Error                           =      "URL Error"
    static let  SW_Error                            =      "Web service error"
    
    //TODO: Errors keys
    static let  errorMessage_Key                    =      "errorMessage"
}
